/**
 * Created by mariustanawatsamo on 24/07/2017.
 */
// Getters
export const GET_CURRENT_LOGGED_USER_NAME = 'GET_CURRENT_LOGGED_USER_NAME'
export const GET_CURRENT_LOGGED_USER_PRENOM = 'GET_CURRENT_LOGGED_USER_PRENOM'
export const GET_CURRENT_LOGGED_USER_EMAIL = 'GET_CURRENT_LOGGED_USER_EMAIL'
export const GET_CURRENT_LOGGED_USER_PASSWORD = 'GET_CURRENT_LOGGED_USER_PASSWORD'

// Mutations
export const CHANGE_CREDENTIALS_CURRENT_USER_NAME = 'CHANGE_CREDENTIALS_CURRENT_USER_NAME'
export const CHANGE_CREDENTIALS_CURRENT_USER_EMAIL = 'CHANGE_CREDENTIALS_CURRENT_USER_EMAIL'
export const CHANGE_CREDENTIALS_CURRENT_USER_PRENOM = 'CHANGE_CREDENTIALS_CURRENT_USER_PRENOM'
export const CHANGE_CREDENTIALS_CURRENT_USER_PASSWORD = 'CHANGE_CREDENTIALS_CURRENT_USER_PASSWORD'

// ACTIONS
export const SET_CREDENTIALS_CURRENT_USER_NAME = 'SET_CREDENTIALS_CURRENT_USER_NAME'
export const SET_CREDENTIALS_CURRENT_USER_EMAIL = 'SET_CREDENTIALS_CURRENT_USER_EMAIL'
export const SET_CREDENTIALS_CURRENT_USER_PRENOM = 'SET_CREDENTIALS_CURRENT_USER_PRENOM'
export const SET_CREDENTIALS_CURRENT_USER_PASSWORD = 'SET_CREDENTIALS_CURRENT_USER_PASSWORD'
